### ISSUE TITLE
Deploy Plausible to ECS

### ISSUE THREAD

**Issue by pcr0wley** [crowleysystems/analytics#1]
This issue is to deploy Plausible to ECS. Currently it is running in Docker on EC2.

### `docker-compose.yml`
```
version: "3.3"
services:
  plausible:
    image: plausible/analytics:v2.0.0-rc.4
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    ports:
      - 80:80
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
```

### `plausible-conf.env`
```
BASE_URL=https://plausible.crowleymarine.com
PORT=80
SECRET_KEY_BASE=secret_key_base
MAILER_ADAPTER=Bamboo.PostmarkAdapter
POSTMARK_API_KEY=postmark_api_key
MAILER_EMAIL=support@crowleymarine.com

# For Google Analytics data import
GOOGLE_CLIENT_ID=google_client_id
GOOGLE_CLIENT_SECRET=google_client_secret

DATABASE_URL=postgres://plausible:PASSWORD@HOST:5432/plausible

CLICKHOUSE_DATABASE_URL=https://plausible:PASSWORD@HOST:8443/plausible_events_db
```
